name: Notify Discord

on:
  workflow_dispatch: # æ‰‹å‹•ãƒˆãƒªã‚¬ãƒ¼ã‚’è¿½åŠ 
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set_result.outputs.result }}
    steps:
      - name: Build and Deploy
        id: build
        run: |
          echo "ãƒ“ãƒ«ãƒ‰ã¨ãƒ‡ãƒ—ãƒ­ã‚¤ãŒæˆåŠŸã—ã¾ã—ãŸ"
          echo "success" > result.txt 

      - name: Set result variable
        id: set_result
        run: |
          result=$(cat result.txt)
          echo "::set-output name=result::$result"

  notify:
    runs-on: ubuntu-latest
    needs: build_and_deploy
    steps:
      - name: Discord Message Notify
        run: |
          # GitHubãƒªãƒã‚¸ãƒˆãƒªã®URLã¨Actionsã®å®Ÿè¡ŒIDã‚’å–å¾—
          REPO_URL="https://github.com/${{ github.repository }}"
          RUN_ID="${{ github.run_id }}"
          LOG_URL="${REPO_URL}/actions/runs/${RUN_ID}"

          # å®Ÿè¡Œçµæœã«å¿œã˜ãŸãƒ¡ãƒƒã‚»ãƒ¼ã‚¸ã‚’è¨­å®š
          if [[ "${{ needs.build_and_deploy.outputs.result }}" == "success" ]]; then
            message='{"content": "ãƒ“ãƒ«ãƒ‰ã¨ãƒ‡ãƒ—ãƒ­ã‚¤ãŒæˆåŠŸã—ã¾ã—ãŸï¼ ğŸ‰ å®Ÿè¡Œãƒ­ã‚°ã¯ã“ã¡ã‚‰: '"$LOG_URL"'"}'
          else
            message='{"content": "ãƒ“ãƒ«ãƒ‰ã¨ãƒ‡ãƒ—ãƒ­ã‚¤ã«å¤±æ•—ã—ã¾ã—ãŸã€‚ã‚¨ãƒ©ãƒ¼ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸ã‚’ç¢ºèªã—ã¦ãã ã•ã„ã€‚ âŒ å®Ÿè¡Œãƒ­ã‚°ã¯ã“ã¡ã‚‰: '"$LOG_URL"'"}'
          fi
        
          # Discordã«ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸ã‚’é€ä¿¡
          curl -X POST -H 'Content-Type: application/json' --data "$message" ${{ secrets.DISCORD_WEBHOOK_URL }}
